// Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v2alpha1 "github.com/ZupIT/horusec-admin/pkg/api/install/v2alpha1"
)

// FakeHorusecPlatforms implements HorusecPlatformInterface
type FakeHorusecPlatforms struct {
	Fake *FakeInstallV2alpha1
	ns   string
}

var horusecplatformsResource = schema.GroupVersionResource{Group: "install.horusec.io", Version: "v2alpha1", Resource: "horusecplatforms"}

var horusecplatformsKind = schema.GroupVersionKind{Group: "install.horusec.io", Version: "v2alpha1", Kind: "HorusecPlatform"}

// Get takes name of the horusecPlatform, and returns the corresponding horusecPlatform object, and an error if there is any.
func (c *FakeHorusecPlatforms) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.HorusecPlatform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(horusecplatformsResource, c.ns, name), &v2alpha1.HorusecPlatform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.HorusecPlatform), err
}

// List takes label and field selectors, and returns the list of HorusecPlatforms that match those selectors.
func (c *FakeHorusecPlatforms) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.HorusecPlatformList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(horusecplatformsResource, horusecplatformsKind, c.ns, opts), &v2alpha1.HorusecPlatformList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.HorusecPlatformList{ListMeta: obj.(*v2alpha1.HorusecPlatformList).ListMeta}
	for _, item := range obj.(*v2alpha1.HorusecPlatformList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested horusecPlatforms.
func (c *FakeHorusecPlatforms) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(horusecplatformsResource, c.ns, opts))

}

// Create takes the representation of a horusecPlatform and creates it.  Returns the server's representation of the horusecPlatform, and an error, if there is any.
func (c *FakeHorusecPlatforms) Create(ctx context.Context, horusecPlatform *v2alpha1.HorusecPlatform, opts v1.CreateOptions) (result *v2alpha1.HorusecPlatform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(horusecplatformsResource, c.ns, horusecPlatform), &v2alpha1.HorusecPlatform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.HorusecPlatform), err
}

// Update takes the representation of a horusecPlatform and updates it. Returns the server's representation of the horusecPlatform, and an error, if there is any.
func (c *FakeHorusecPlatforms) Update(ctx context.Context, horusecPlatform *v2alpha1.HorusecPlatform, opts v1.UpdateOptions) (result *v2alpha1.HorusecPlatform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(horusecplatformsResource, c.ns, horusecPlatform), &v2alpha1.HorusecPlatform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.HorusecPlatform), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHorusecPlatforms) UpdateStatus(ctx context.Context, horusecPlatform *v2alpha1.HorusecPlatform, opts v1.UpdateOptions) (*v2alpha1.HorusecPlatform, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(horusecplatformsResource, "status", c.ns, horusecPlatform), &v2alpha1.HorusecPlatform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.HorusecPlatform), err
}

// Delete takes name of the horusecPlatform and deletes it. Returns an error if one occurs.
func (c *FakeHorusecPlatforms) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(horusecplatformsResource, c.ns, name), &v2alpha1.HorusecPlatform{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHorusecPlatforms) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(horusecplatformsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.HorusecPlatformList{})
	return err
}

// Patch applies the patch and returns the patched horusecPlatform.
func (c *FakeHorusecPlatforms) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.HorusecPlatform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(horusecplatformsResource, c.ns, name, pt, data, subresources...), &v2alpha1.HorusecPlatform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.HorusecPlatform), err
}
