// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package router

import (
	"github.com/go-chi/chi"
	"github.com/google/wire"
	"github.com/tiagoangelozup/horusec-admin/internal/http/handler"
	"github.com/tiagoangelozup/horusec-admin/internal/http/middleware"
	"github.com/tiagoangelozup/horusec-admin/internal/http/render"
)

// Injectors from wire.go:

func newRouter() (*router, error) {
	mux := chi.NewRouter()
	authorizer := middleware.NewAuthorizer()
	rendererRender := render.New()
	v, err := scanPages(rendererRender)
	if err != nil {
		return nil, err
	}
	auth := handler.NewAuth()
	configEditing := handler.NewConfigEditing(rendererRender)
	configReading := handler.NewConfigReading(rendererRender)
	health := handler.NewHealth()
	routerHandlers := &handlers{
		Auth:          auth,
		ConfigEditing: configEditing,
		ConfigReading: configReading,
		Health:        health,
	}
	v2 := newAPIs(routerHandlers)
	routerRouter := &router{
		Mux:    mux,
		authz:  authorizer,
		render: rendererRender,
		Pages:  v,
		APIs:   v2,
	}
	return routerRouter, nil
}

// wire.go:

var providers = wire.NewSet(chi.NewRouter, handler.NewAuth, handler.NewConfigEditing, handler.NewConfigReading, handler.NewHealth, middleware.NewAuthorizer, render.New, newAPIs,
	scanPages, wire.Struct(new(handlers), "*"), wire.Struct(new(router), "*"),
)
