// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package router

import (
	"github.com/go-chi/chi"
	"github.com/google/wire"
	"github.com/tiagoangelozup/horusec-admin/internal/http/handler"
	"github.com/tiagoangelozup/horusec-admin/internal/http/middleware"
	"github.com/tiagoangelozup/horusec-admin/internal/http/render"
)

// Injectors from wire.go:

func newRouter() *router {
	mux := chi.NewRouter()
	authorizer := middleware.NewAuthorizer()
	auth := handler.NewAuth()
	rendererRender := render.New()
	configEditing := handler.NewConfigEditing(rendererRender)
	configReading := handler.NewConfigReading(rendererRender)
	health := handler.NewHealth()
	routerHandlers := &handlers{
		Auth:          auth,
		ConfigEditing: configEditing,
		ConfigReading: configReading,
		Health:        health,
	}
	v := newRoutes(routerHandlers)
	routerRouter := &router{
		Mux:    mux,
		authz:  authorizer,
		Routes: v,
	}
	return routerRouter
}

// wire.go:

var providers = wire.NewSet(chi.NewRouter, handler.NewAuth, handler.NewConfigEditing, handler.NewConfigReading, handler.NewHealth, middleware.NewAuthorizer, newRoutes, render.New, wire.Struct(new(handlers), "*"), wire.Struct(new(router), "*"))
