// Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v2alpha1 "github.com/ZupIT/horusec-admin/pkg/api/install/v2alpha1"
	scheme "github.com/ZupIT/horusec-admin/pkg/client/clientset/versioned/scheme"
)

// HorusecPlatformsGetter has a method to return a HorusecPlatformInterface.
// A group's client should implement this interface.
type HorusecPlatformsGetter interface {
	HorusecPlatforms(namespace string) HorusecPlatformInterface
}

// HorusecPlatformInterface has methods to work with HorusecPlatform resources.
type HorusecPlatformInterface interface {
	Create(ctx context.Context, horusecPlatform *v2alpha1.HorusecPlatform, opts v1.CreateOptions) (*v2alpha1.HorusecPlatform, error)
	Update(ctx context.Context, horusecPlatform *v2alpha1.HorusecPlatform, opts v1.UpdateOptions) (*v2alpha1.HorusecPlatform, error)
	UpdateStatus(ctx context.Context, horusecPlatform *v2alpha1.HorusecPlatform, opts v1.UpdateOptions) (*v2alpha1.HorusecPlatform, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.HorusecPlatform, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.HorusecPlatformList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.HorusecPlatform, err error)
	HorusecPlatformExpansion
}

// horusecPlatforms implements HorusecPlatformInterface
type horusecPlatforms struct {
	client rest.Interface
	ns     string
}

// newHorusecPlatforms returns a HorusecPlatforms
func newHorusecPlatforms(c *InstallV2alpha1Client, namespace string) *horusecPlatforms {
	return &horusecPlatforms{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the horusecPlatform, and returns the corresponding horusecPlatform object, and an error if there is any.
func (c *horusecPlatforms) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.HorusecPlatform, err error) {
	result = &v2alpha1.HorusecPlatform{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("horusecplatforms").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HorusecPlatforms that match those selectors.
func (c *horusecPlatforms) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.HorusecPlatformList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.HorusecPlatformList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("horusecplatforms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested horusecPlatforms.
func (c *horusecPlatforms) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("horusecplatforms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a horusecPlatform and creates it.  Returns the server's representation of the horusecPlatform, and an error, if there is any.
func (c *horusecPlatforms) Create(ctx context.Context, horusecPlatform *v2alpha1.HorusecPlatform, opts v1.CreateOptions) (result *v2alpha1.HorusecPlatform, err error) {
	result = &v2alpha1.HorusecPlatform{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("horusecplatforms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(horusecPlatform).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a horusecPlatform and updates it. Returns the server's representation of the horusecPlatform, and an error, if there is any.
func (c *horusecPlatforms) Update(ctx context.Context, horusecPlatform *v2alpha1.HorusecPlatform, opts v1.UpdateOptions) (result *v2alpha1.HorusecPlatform, err error) {
	result = &v2alpha1.HorusecPlatform{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("horusecplatforms").
		Name(horusecPlatform.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(horusecPlatform).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *horusecPlatforms) UpdateStatus(ctx context.Context, horusecPlatform *v2alpha1.HorusecPlatform, opts v1.UpdateOptions) (result *v2alpha1.HorusecPlatform, err error) {
	result = &v2alpha1.HorusecPlatform{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("horusecplatforms").
		Name(horusecPlatform.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(horusecPlatform).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the horusecPlatform and deletes it. Returns an error if one occurs.
func (c *horusecPlatforms) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("horusecplatforms").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *horusecPlatforms) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("horusecplatforms").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched horusecPlatform.
func (c *horusecPlatforms) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.HorusecPlatform, err error) {
	result = &v2alpha1.HorusecPlatform{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("horusecplatforms").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
