/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	installv1alpha1 "github.com/tiagoangelozup/horusec-admin/pkg/api/install/v1alpha1"
	versioned "github.com/tiagoangelozup/horusec-admin/pkg/client/clientset/versioned"
	internalinterfaces "github.com/tiagoangelozup/horusec-admin/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/tiagoangelozup/horusec-admin/pkg/client/listers/install/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HorusecManagerSpecInformer provides access to a shared informer and lister for
// HorusecManagerSpecs.
type HorusecManagerSpecInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.HorusecManagerSpecLister
}

type horusecManagerSpecInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHorusecManagerSpecInformer constructs a new informer for HorusecManagerSpec type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHorusecManagerSpecInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHorusecManagerSpecInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHorusecManagerSpecInformer constructs a new informer for HorusecManagerSpec type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHorusecManagerSpecInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InstallV1alpha1().HorusecManagerSpecs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InstallV1alpha1().HorusecManagerSpecs(namespace).Watch(context.TODO(), options)
			},
		},
		&installv1alpha1.HorusecManagerSpec{},
		resyncPeriod,
		indexers,
	)
}

func (f *horusecManagerSpecInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHorusecManagerSpecInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *horusecManagerSpecInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&installv1alpha1.HorusecManagerSpec{}, f.defaultInformer)
}

func (f *horusecManagerSpecInformer) Lister() v1alpha1.HorusecManagerSpecLister {
	return v1alpha1.NewHorusecManagerSpecLister(f.Informer().GetIndexer())
}
