// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/tiagoangelozup/horusec-admin/pkg/client/clientset/versioned/typed/install/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeInstallV1alpha1 struct {
	*testing.Fake
}

func (c *FakeInstallV1alpha1) HorusecManagers(namespace string) v1alpha1.HorusecManagerInterface {
	return &FakeHorusecManagers{c, namespace}
}

func (c *FakeInstallV1alpha1) HorusecManagerSpecs(namespace string) v1alpha1.HorusecManagerSpecInterface {
	return &FakeHorusecManagerSpecs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeInstallV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
