// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package router

import (
	"github.com/ZupIT/horusec-admin/internal/authz"
	"github.com/ZupIT/horusec-admin/internal/router/api"
	"github.com/ZupIT/horusec-admin/internal/router/handler"
	"github.com/ZupIT/horusec-admin/internal/router/middleware"
	"github.com/ZupIT/horusec-admin/internal/router/page"
	"github.com/ZupIT/horusec-admin/internal/router/render"
	"github.com/ZupIT/horusec-admin/internal/router/static"
	"github.com/ZupIT/horusec-admin/pkg/core"
	"github.com/go-chi/chi"
	"github.com/google/wire"
)

// Injectors from wire.go:

func newRouter(reader core.ConfigurationReader, writer core.ConfigurationWriter) (*router, error) {
	mux := chi.NewRouter()
	authzAuthz := authz.New()
	authorizer := middleware.NewAuthorizer(authzAuthz)
	rendererRender := render.New()
	traceInitializer := middleware.NewTracer()
	auth := handler.NewAuth()
	configEditing := handler.NewConfigEditing(rendererRender, writer)
	configReading := handler.NewConfigReading(rendererRender, reader)
	health := handler.NewHealth()
	handlers := &api.Handlers{
		Auth:          auth,
		ConfigEditing: configEditing,
		ConfigReading: configReading,
		Health:        health,
	}
	set := api.NewSet(handlers)
	assets, err := static.ListAssets()
	if err != nil {
		return nil, err
	}
	defaultRender := handler.NewDefaultRender(rendererRender)
	pageSet := page.NewSet(defaultRender)
	routerRouter := &router{
		Mux:    mux,
		authz:  authorizer,
		render: rendererRender,
		tracer: traceInitializer,
		APIs:   set,
		Assets: assets,
		Pages:  pageSet,
	}
	return routerRouter, nil
}

// wire.go:

var providers = wire.NewSet(api.NewSet, chi.NewRouter, handler.NewAuth, handler.NewConfigEditing, handler.NewConfigReading, handler.NewDefaultRender, handler.NewHealth, middleware.NewAuthorizer, middleware.NewTracer, authz.New, page.NewSet, render.New, static.ListAssets, wire.Struct(new(api.Handlers), "*"), wire.Struct(new(router), "*"))
